import Head from 'next/head'
import Header from './header'
import Nav from './nav'

export default function Layout({ children }) {
  return (
    <div className="mx-auto p-6">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Nav />
      <main>{ children }</main>
    </div>
  )
}